name: cellsnake
channels:
 - conda-forge
 - bioconda
 - anaconda
dependencies:
 - celltypist ==1.3.0
 - docopt
 - fuzzywuzzy
 - levenshtein
 - matplotlib-base <3.7
 - pandas <=1.5.3
 - pysam >=0.16.0.1
 - python
 - regex >=2021.4.4
 - scipy 
 - snakemake >=7.22.0
 - umap-learn
 - plotly
 - python-kaleido
 - r-base==4.2.2
 - r-igraph==1.3.4
 - r-ggraph==2.1.0
 - r-seurat==4.3.0
 - r-clustree==0.5.0
 - r-ggthemes
 - r-viridis
 - r-librarian
 - r-patchwork
 - r-optparse
 - r-openxlsx
 - r-nmf
 - r-fields
 - r-minqa
 - r-ggpubr
 - r-reticulate
 - r-expm
 - r-ggalluvial
 - r-curl
 - r-tidyseurat
 - r-tidyverse
 - r-v8
 - r-plotly
 - r-terra
 - r-r.utils
 - r-spdep
 - r-hdf5r
 - r-monocle3 #version 1.0.0 is the current
 - r-randomcolor
 - bioconductor-rhdf5lib
 - bioconductor-clusterprofiler==4.6.0
 - bioconductor-scater==1.26.0
 - bioconductor-limma
 - bioconductor-complexheatmap
 - bioconductor-topgo
 - bioconductor-org.hs.eg.db
 - bioconductor-miqc 
 - bioconductor-rhdf5lib
 - bioconductor-singler
 - bioconductor-celldex
 - bioconductor-enhancedvolcano
 - geos==3.11.1
 - cmake
 - hdf5
 - numba>=0.56.4
 - r-xml
 - bedtools
 - samtools
 - pandoc==3.1.1
 - kraken2
 - openblas==0.3.21
 - pip
 - scanpy>=1.9.1
 - cython
# - pip:
#   - scipy>=1.6.2
#   - regex>=2021.4.4
#   - pysam>=0.16.0.1
#   - matplotlib<3.7
#   - celltypist==1.3.0
#   - pandas
#   - levenshtein
#   - fuzzywuzzy
#   - docopt
#   - snakemake>=7.22.0
#   - umap-learn
#   - plotly
#   - kaleido
